INSERT wtf SET acronym_i = 'afaic', acronym = 'AFAIC', text = 'as far as I\'m concerned';
INSERT wtf SET acronym_i = 'afaicr', acronym = 'AFAICR', text = 'as far as I can recall';
INSERT wtf SET acronym_i = 'afaict', acronym = 'AFAICT', text = 'as far as I can tell';
INSERT wtf SET acronym_i = 'afaik', acronym = 'AFAIK', text = 'as far as I know';
INSERT wtf SET acronym_i = 'afair', acronym = 'AFAIR', text = 'as far as I recall';
INSERT wtf SET acronym_i = 'afaiu', acronym = 'AFAIU', text = 'as far as I understand';
INSERT wtf SET acronym_i = 'afd', acronym = 'AFD', text = 'away from desktop';
INSERT wtf SET acronym_i = 'afk', acronym = 'AFK', text = 'away from keyboard';
INSERT wtf SET acronym_i = 'afu', acronym = 'AFU', text = 'all fucked up';
INSERT wtf SET acronym_i = 'afw', acronym = 'AFW', text = 'away from window';
INSERT wtf SET acronym_i = 'aiu', acronym = 'AIU', text = 'as I understand';
INSERT wtf SET acronym_i = 'aiui', acronym = 'AIUI', text = 'as I understand it';
INSERT wtf SET acronym_i = 'aka', acronym = 'AKA', text = 'also known as';
INSERT wtf SET acronym_i = 'asaic', acronym = 'ASAIC', text = 'as soon as I can';
INSERT wtf SET acronym_i = 'asap', acronym = 'ASAP', text = 'as soon as possible';
INSERT wtf SET acronym_i = 'atm', acronym = 'ATM', text = 'at the moment';
INSERT wtf SET acronym_i = 'awol', acronym = 'AWOL', text = 'absent without official leave';
INSERT wtf SET acronym_i = 'aybabtu', acronym = 'AYBABTU', text = 'all your base are belong to us';
INSERT wtf SET acronym_i = 'ayt', acronym = 'AYT', text = 'are you there';
INSERT wtf SET acronym_i = 'b/c', acronym = 'B/C', text = 'because';
INSERT wtf SET acronym_i = 'b/s', acronym = 'B/S', text = 'bullshit';
INSERT wtf SET acronym_i = 'b/w', acronym = 'B/W', text = 'between';
INSERT wtf SET acronym_i = 'bbiab', acronym = 'BBIAB', text = 'be back in a bit';
INSERT wtf SET acronym_i = 'bbl', acronym = 'BBL', text = '[I\'ll] be back later';
INSERT wtf SET acronym_i = 'bbs', acronym = 'BBS', text = 'be back soon';
INSERT wtf SET acronym_i = 'bbt', acronym = 'BBT', text = 'be back tomorrow';
INSERT wtf SET acronym_i = 'bfd', acronym = 'BFD', text = 'big fucking deal';
INSERT wtf SET acronym_i = 'biab', acronym = 'BIAB', text = 'back in a bit';
INSERT wtf SET acronym_i = 'biaf', acronym = 'BIAF', text = 'back in a few';
INSERT wtf SET acronym_i = 'bialw', acronym = 'BIALW', text = 'back in a little while';
INSERT wtf SET acronym_i = 'bias', acronym = 'BIAS', text = 'back in a second';
INSERT wtf SET acronym_i = 'biaw', acronym = 'BIAW', text = 'back in a while';
INSERT wtf SET acronym_i = 'boatilas', acronym = 'BOATILAS', text = 'bend over and take it like a slut';
INSERT wtf SET acronym_i = 'bofh', acronym = 'BOFH', text = 'bastard operator from hell';
INSERT wtf SET acronym_i = 'bogahica', acronym = 'BOGAHICA', text = 'bend over, grab ankles, here it comes again';
INSERT wtf SET acronym_i = 'bohica', acronym = 'BOHICA', text = 'bend over here it comes again';
INSERT wtf SET acronym_i = 'brb', acronym = 'BRB', text = '[I\'ll] be right back';
INSERT wtf SET acronym_i = 'bs', acronym = 'BS', text = 'bullshit';
INSERT wtf SET acronym_i = 'btdt', acronym = 'BTDT', text = 'been there, done that';
INSERT wtf SET acronym_i = 'btth', acronym = 'BTTH', text = 'boot to the head';
INSERT wtf SET acronym_i = 'btw', acronym = 'BTW', text = 'by the way';
INSERT wtf SET acronym_i = 'cmiiw', acronym = 'CMIIW', text = 'correct me if I\'m wrong';
INSERT wtf SET acronym_i = 'cnp', acronym = 'CNP', text = 'continued [in my] next post';
INSERT wtf SET acronym_i = 'cob', acronym = 'COB', text = 'close of business [day]';
INSERT wtf SET acronym_i = 'cots', acronym = 'COTS', text = 'commercial off-the-shelf';
INSERT wtf SET acronym_i = 'cya', acronym = 'CYA', text = 'see you around';
INSERT wtf SET acronym_i = 'd/l', acronym = 'D/L', text = 'download';
INSERT wtf SET acronym_i = 'diy', acronym = 'DIY', text = 'do it yourself';
INSERT wtf SET acronym_i = 'dkdc', acronym = 'DKDC', text = 'don\'t know, don\'t care';
INSERT wtf SET acronym_i = 'dstm', acronym = 'DSTM', text = 'don\'t shoot the messenger';
INSERT wtf SET acronym_i = 'dtrt', acronym = 'DTRT', text = 'do the right thing';
INSERT wtf SET acronym_i = 'dtwt', acronym = 'DTWT', text = 'do the wrong thing';
INSERT wtf SET acronym_i = 'dwim', acronym = 'DWIM', text = 'do what I mean';
INSERT wtf SET acronym_i = 'eg', acronym = 'EG', text = 'evil grin';
INSERT wtf SET acronym_i = 'emsg', acronym = 'EMSG', text = 'email message';
INSERT wtf SET acronym_i = 'eob', acronym = 'EOB', text = 'end of business [day]';
INSERT wtf SET acronym_i = 'eod', acronym = 'EOD', text = 'end of discussion';
INSERT wtf SET acronym_i = 'eol', acronym = 'EOL', text = 'end of life';
INSERT wtf SET acronym_i = 'etla', acronym = 'ETLA', text = 'extended three letter acronym';
INSERT wtf SET acronym_i = 'ewag', acronym = 'EWAG', text = 'experienced wild-ass guess';
INSERT wtf SET acronym_i = 'faq', acronym = 'FAQ', text = 'frequently asked question';
INSERT wtf SET acronym_i = 'fcfs', acronym = 'FCFS', text = 'first come first served';
INSERT wtf SET acronym_i = 'figjam', acronym = 'FIGJAM', text = 'fuck I\'m good, just ask me';
INSERT wtf SET acronym_i = 'fiik', acronym = 'FIIK', text = 'fuck[ed] if I know';
INSERT wtf SET acronym_i = 'fiir', acronym = 'FIIR', text = 'fuck[ed] if I remember';
INSERT wtf SET acronym_i = 'fm', acronym = 'FM', text = 'fucking magic';
INSERT wtf SET acronym_i = 'foad', acronym = 'FOAD', text = 'fall over and die';
INSERT wtf SET acronym_i = 'fsdo', acronym = 'FSDO', text = 'for some definition of';
INSERT wtf SET acronym_i = 'fsvo', acronym = 'FSVO', text = 'for some value of';
INSERT wtf SET acronym_i = 'ftfm', acronym = 'FTFM', text = 'fuck the fuckin\' manual!';
INSERT wtf SET acronym_i = 'fubar', acronym = 'FUBAR', text = 'fucked up beyond all recognition';
INSERT wtf SET acronym_i = 'fud', acronym = 'FUD', text = 'fear, uncertainty and doubt';
INSERT wtf SET acronym_i = 'fwiw', acronym = 'FWIW', text = 'for what it\'s worth';
INSERT wtf SET acronym_i = 'fyi', acronym = 'FYI', text = 'for your information';
INSERT wtf SET acronym_i = 'g', acronym = 'G', text = 'grin';
INSERT wtf SET acronym_i = 'g/c', acronym = 'G/C', text = 'garbage collect';
INSERT wtf SET acronym_i = 'gac', acronym = 'GAC', text = 'get a clue';
INSERT wtf SET acronym_i = 'gal', acronym = 'GAL', text = 'get a life';
INSERT wtf SET acronym_i = 'gigo', acronym = 'GIGO', text = 'garbage in, garbage out';
INSERT wtf SET acronym_i = 'gmta', acronym = 'GMTA', text = 'great minds think alike';
INSERT wtf SET acronym_i = 'gtfo', acronym = 'GTFO', text = 'get the fuck out';
INSERT wtf SET acronym_i = 'gtg', acronym = 'GTG', text = 'got to go';
INSERT wtf SET acronym_i = 'hand', acronym = 'HAND', text = 'have a nice day';
INSERT wtf SET acronym_i = 'hhis', acronym = 'HHIS', text = 'hanging head in shame';
INSERT wtf SET acronym_i = 'hica', acronym = 'HICA', text = 'here it comes again';
INSERT wtf SET acronym_i = 'hth', acronym = 'HTH', text = 'hope this helps';
INSERT wtf SET acronym_i = 'iac', acronym = 'IAC', text = 'in any case';
INSERT wtf SET acronym_i = 'ianal', acronym = 'IANAL', text = 'I am not a lawyer';
INSERT wtf SET acronym_i = 'ic', acronym = 'IC', text = 'I see';
INSERT wtf SET acronym_i = 'icbw', acronym = 'ICBW', text = 'I could be wrong';
INSERT wtf SET acronym_i = 'iccl', acronym = 'ICCL', text = 'I couldn\'t care less';
INSERT wtf SET acronym_i = 'ihafc', acronym = 'IHAFC', text = 'I haven\'t a fucking clue';
INSERT wtf SET acronym_i = 'ihbw', acronym = 'IHBW', text = 'I have been wrong';
INSERT wtf SET acronym_i = 'ihnfc', acronym = 'IHNFC', text = 'I have no fucking clue';
INSERT wtf SET acronym_i = 'iianm', acronym = 'IIANM', text = 'if I am not mistaken';
INSERT wtf SET acronym_i = 'iirc', acronym = 'IIRC', text = 'if I recall correctly';
INSERT wtf SET acronym_i = 'iiuc', acronym = 'IIUC', text = 'if I understand correctly';
INSERT wtf SET acronym_i = 'imao', acronym = 'IMAO', text = 'in my arrogant opinion';
INSERT wtf SET acronym_i = 'imco', acronym = 'IMCO', text = 'in my considered opinion';
INSERT wtf SET acronym_i = 'imho', acronym = 'IMHO', text = 'in my humble opinion';
INSERT wtf SET acronym_i = 'imnsho', acronym = 'IMNSHO', text = 'in my not so humble opinion';
INSERT wtf SET acronym_i = 'imo', acronym = 'IMO', text = 'in my opinion';
INSERT wtf SET acronym_i = 'iow', acronym = 'IOW', text = 'in other words';
INSERT wtf SET acronym_i = 'irl', acronym = 'IRL', text = 'in real life';
INSERT wtf SET acronym_i = 'isagn', acronym = 'ISAGN', text = 'I see a great need';
INSERT wtf SET acronym_i = 'istm', acronym = 'ISTM', text = 'it seems to me';
INSERT wtf SET acronym_i = 'istr', acronym = 'ISTR', text = 'I seem to recall';
INSERT wtf SET acronym_i = 'itym', acronym = 'ITYM', text = 'I think you mean';
INSERT wtf SET acronym_i = 'iwbni', acronym = 'IWBNI', text = 'it would be nice if';
INSERT wtf SET acronym_i = 'iyss', acronym = 'IYSS', text = 'if you say so';
INSERT wtf SET acronym_i = 'j/k', acronym = 'J/K', text = 'just kidding';
INSERT wtf SET acronym_i = 'jhd', acronym = 'JHD', text = 'just hit ``delete\'\'';
INSERT wtf SET acronym_i = 'jic', acronym = 'JIC', text = 'just in case';
INSERT wtf SET acronym_i = 'jk', acronym = 'JK', text = 'just kidding';
INSERT wtf SET acronym_i = 'jmo', acronym = 'JMO', text = 'just my opinion';
INSERT wtf SET acronym_i = 'jtlyk', acronym = 'JTLYK', text = 'just to let you know';
INSERT wtf SET acronym_i = 'kiss', acronym = 'KISS', text = 'keep it simple, stupid';
INSERT wtf SET acronym_i = 'kita', acronym = 'KITA', text = 'kick in the ass';
INSERT wtf SET acronym_i = 'knf', acronym = 'KNF', text = 'kernel normal form';
INSERT wtf SET acronym_i = 'l8r', acronym = 'L8R', text = 'later';
INSERT wtf SET acronym_i = 'lart', acronym = 'LART', text = 'luser attitude readjustment tool (ie, hammer)';
INSERT wtf SET acronym_i = 'lbnl', acronym = 'LBNL', text = 'last but not least';
INSERT wtf SET acronym_i = 'ljbf', acronym = 'LJBF', text = 'let\'s just be friends';
INSERT wtf SET acronym_i = 'lmao', acronym = 'LMAO', text = 'laughing my ass off';
INSERT wtf SET acronym_i = 'lmso', acronym = 'LMSO', text = 'laughing my socks off';
INSERT wtf SET acronym_i = 'lol', acronym = 'LOL', text = 'laughing out loud';
INSERT wtf SET acronym_i = 'ltns', acronym = 'LTNS', text = 'long time no see';
INSERT wtf SET acronym_i = 'mia', acronym = 'MIA', text = 'missing in action';
INSERT wtf SET acronym_i = 'motas', acronym = 'MOTAS', text = 'member of the appropriate sex';
INSERT wtf SET acronym_i = 'motos', acronym = 'MOTOS', text = 'member of the opposite sex';
INSERT wtf SET acronym_i = 'motss', acronym = 'MOTSS', text = 'member of the same sex';
INSERT wtf SET acronym_i = 'mtf', acronym = 'MTF', text = 'more to follow';
INSERT wtf SET acronym_i = 'myob', acronym = 'MYOB', text = 'mind your own business';
INSERT wtf SET acronym_i = 'n/m', acronym = 'N/M', text = 'never mind';
INSERT wtf SET acronym_i = 'nbd', acronym = 'NBD', text = 'no big deal';
INSERT wtf SET acronym_i = 'nfc', acronym = 'NFC', text = 'no fucking clue';
INSERT wtf SET acronym_i = 'nfi', acronym = 'NFI', text = 'no fucking idea';
INSERT wtf SET acronym_i = 'nfw', acronym = 'NFW', text = 'no fucking way';
INSERT wtf SET acronym_i = 'nih', acronym = 'NIH', text = 'not invented here';
INSERT wtf SET acronym_i = 'nmf', acronym = 'NMF', text = 'not my fault';
INSERT wtf SET acronym_i = 'nmp', acronym = 'NMP', text = 'not my problem';
INSERT wtf SET acronym_i = 'noyb', acronym = 'NOYB', text = 'none of your business';
INSERT wtf SET acronym_i = 'noyfb', acronym = 'NOYFB', text = 'none of your fucking business';
INSERT wtf SET acronym_i = 'np', acronym = 'NP', text = 'no problem';
INSERT wtf SET acronym_i = 'nrfpt', acronym = 'NRFPT', text = 'not ready for prime time';
INSERT wtf SET acronym_i = 'nrn', acronym = 'NRN', text = 'no reply necessary';
INSERT wtf SET acronym_i = 'oic', acronym = 'OIC', text = 'oh, I see';
INSERT wtf SET acronym_i = 'omg', acronym = 'OMG', text = 'oh, my god';
INSERT wtf SET acronym_i = 'ot', acronym = 'OT', text = 'off topic';
INSERT wtf SET acronym_i = 'otl', acronym = 'OTL', text = 'out to lunch';
INSERT wtf SET acronym_i = 'otoh', acronym = 'OTOH', text = 'on the other hand';
INSERT wtf SET acronym_i = 'ott', acronym = 'OTT', text = 'over the top';
INSERT wtf SET acronym_i = 'ottomh', acronym = 'OTTOMH', text = 'off the top of my head';
INSERT wtf SET acronym_i = 'pebkac', acronym = 'PEBKAC', text = 'problem exists between keyboard and chair';
INSERT wtf SET acronym_i = 'pfo', acronym = 'PFO', text = 'please fuck off';
INSERT wtf SET acronym_i = 'pfy', acronym = 'PFY', text = 'pimply faced youth';
INSERT wtf SET acronym_i = 'pita', acronym = 'PITA', text = 'pain in the ass';
INSERT wtf SET acronym_i = 'pksp', acronym = 'PKSP', text = 'pound keys and spew profanity';
INSERT wtf SET acronym_i = 'png', acronym = 'PNG', text = 'persona non grata';
INSERT wtf SET acronym_i = 'pnp', acronym = 'PNP', text = 'plug and pray';
INSERT wtf SET acronym_i = 'poc', acronym = 'POC', text = 'point of contact';
INSERT wtf SET acronym_i = 'pola', acronym = 'POLA', text = 'principle of least astonishment';
INSERT wtf SET acronym_i = 'pols', acronym = 'POLS', text = 'principle of least surprise';
INSERT wtf SET acronym_i = 'pos', acronym = 'POS', text = 'piece of shit';
INSERT wtf SET acronym_i = 'ppl', acronym = 'PPL', text = 'pretty please';
INSERT wtf SET acronym_i = 'ptv', acronym = 'PTV', text = 'parental tunnel vision';
INSERT wtf SET acronym_i = 'qed', acronym = 'QED', text = 'quod erat demonstrandum';
INSERT wtf SET acronym_i = 'rfc', acronym = 'RFC', text = 'request for comments';
INSERT wtf SET acronym_i = 'rip', acronym = 'RIP', text = 'rest in peace';
INSERT wtf SET acronym_i = 'rl', acronym = 'RL', text = 'real life';
INSERT wtf SET acronym_i = 'rlc', acronym = 'RLC', text = 'rod length check';
INSERT wtf SET acronym_i = 'rofl', acronym = 'ROFL', text = 'rolling on floor laughing';
INSERT wtf SET acronym_i = 'roflmao', acronym = 'ROFLMAO', text = 'rolling on floor laughing my ass off';
INSERT wtf SET acronym_i = 'rotfl', acronym = 'ROTFL', text = 'rolling on the floor laughing';
INSERT wtf SET acronym_i = 'rp', acronym = 'RP', text = 'responsible person';
INSERT wtf SET acronym_i = 'rsn', acronym = 'RSN', text = 'real soon now';
INSERT wtf SET acronym_i = 'rtfb', acronym = 'RTFB', text = 'read the fine/fucking book';
INSERT wtf SET acronym_i = 'rtfc', acronym = 'RTFC', text = 'read the fine/fucking code';
INSERT wtf SET acronym_i = 'rtfd', acronym = 'RTFD', text = 'read the fine/fucking documentation';
INSERT wtf SET acronym_i = 'rtfm', acronym = 'RTFM', text = 'read the fine/fucking manual';
INSERT wtf SET acronym_i = 'rtfmp', acronym = 'RTFMP', text = 'read the fine/fucking man page';
INSERT wtf SET acronym_i = 'rtfs', acronym = 'RTFS', text = 'read the fine/fucking source';
INSERT wtf SET acronym_i = 'scnr', acronym = 'SCNR', text = 'sorry, could not resist';
INSERT wtf SET acronym_i = 'sep', acronym = 'SEP', text = 'someone else\'s problem';
INSERT wtf SET acronym_i = 'sfa', acronym = 'SFA', text = 'sweet fuck all';
INSERT wtf SET acronym_i = 'shid', acronym = 'SHID', text = 'slaps head in disgust';
INSERT wtf SET acronym_i = 'simca', acronym = 'SIMCA', text = 'sitting in my chair amused';
INSERT wtf SET acronym_i = 'smlsfb', acronym = 'SMLSFB', text = 'so many losers, so few bullets';
INSERT wtf SET acronym_i = 'smop', acronym = 'SMOP', text = 'simple matter of programming';
INSERT wtf SET acronym_i = 'snafu', acronym = 'SNAFU', text = 'situation normal, all fucked up';
INSERT wtf SET acronym_i = 'snert', acronym = 'SNERT', text = 'snot-nosed egotistical rude teenager';
INSERT wtf SET acronym_i = 'snmp', acronym = 'SNMP', text = 'sorry, not my problem';
INSERT wtf SET acronym_i = 'snr', acronym = 'SNR', text = 'signal to noise ratio';
INSERT wtf SET acronym_i = 'so', acronym = 'SO', text = 'significant other';
INSERT wtf SET acronym_i = 'sob', acronym = 'SOB', text = 'son of [a] bitch';
INSERT wtf SET acronym_i = 'sol', acronym = 'SOL', text = 'shit out [of] luck';
INSERT wtf SET acronym_i = 'sop', acronym = 'SOP', text = 'standard operating procedure';
INSERT wtf SET acronym_i = 'ssia', acronym = 'SSIA', text = 'subject says it all';
INSERT wtf SET acronym_i = 'stfa', acronym = 'STFA', text = 'search the fucking archives';
INSERT wtf SET acronym_i = 'stfu', acronym = 'STFU', text = 'shut the fuck up';
INSERT wtf SET acronym_i = 'stfw', acronym = 'STFW', text = 'search the fucking web';
INSERT wtf SET acronym_i = 'sus', acronym = 'SUS', text = 'stupid user syndrome';
INSERT wtf SET acronym_i = 'swag', acronym = 'SWAG', text = 'silly, wild-assed guess';
INSERT wtf SET acronym_i = 'swahbi', acronym = 'SWAHBI', text = 'silly, wild-assed hare-brained idea';
INSERT wtf SET acronym_i = 'swmbo', acronym = 'SWMBO', text = 'she who must be obeyed';
INSERT wtf SET acronym_i = 'tanstaafl', acronym = 'TANSTAAFL', text = 'there ain\'t no such thing as a free lunch';
INSERT wtf SET acronym_i = 'tbc', acronym = 'TBC', text = 'to be continued';
INSERT wtf SET acronym_i = 'tbd', acronym = 'TBD', text = 'to be {decided,determined,done}';
INSERT wtf SET acronym_i = 'tbomk', acronym = 'TBOMK', text = 'the best of my knowledge';
INSERT wtf SET acronym_i = 'thnx', acronym = 'THNX', text = 'thanks';
INSERT wtf SET acronym_i = 'thx', acronym = 'THX', text = 'thanks';
INSERT wtf SET acronym_i = 'tia', acronym = 'TIA', text = 'thanks in advance';
INSERT wtf SET acronym_i = 'tinc', acronym = 'TINC', text = 'there is no cabal';
INSERT wtf SET acronym_i = 'tla', acronym = 'TLA', text = 'three letter acronym';
INSERT wtf SET acronym_i = 'tlb', acronym = 'TLB', text = 'translation lookaside buffer';
INSERT wtf SET acronym_i = 'tma', acronym = 'TMA', text = 'too many abbreviations';
INSERT wtf SET acronym_i = 'tmi', acronym = 'TMI', text = 'too much information';
INSERT wtf SET acronym_i = 'tnf', acronym = 'TNF', text = 'The NetBSD Foundation';
INSERT wtf SET acronym_i = 'toefl', acronym = 'TOEFL', text = 'test of english as a foreign language';
INSERT wtf SET acronym_i = 'tptb', acronym = 'TPTB', text = 'the powers that be';
INSERT wtf SET acronym_i = 'trt', acronym = 'TRT', text = 'the right thing';
INSERT wtf SET acronym_i = 'ttbomk', acronym = 'TTBOMK', text = 'to the best of my knowledge';
INSERT wtf SET acronym_i = 'ttfn', acronym = 'TTFN', text = 'ta ta for now';
INSERT wtf SET acronym_i = 'ttyl', acronym = 'TTYL', text = 'talk to you later';
INSERT wtf SET acronym_i = 'twiavbp', acronym = 'TWIAVBP', text = 'the world is a very big place';
INSERT wtf SET acronym_i = 'ty', acronym = 'TY', text = 'thank you';
INSERT wtf SET acronym_i = 'tyvm', acronym = 'TYVM', text = 'thank you very much';
INSERT wtf SET acronym_i = 'u/l', acronym = 'U/L', text = 'upload';
INSERT wtf SET acronym_i = 'utsl', acronym = 'UTSL', text = 'use the source, Luke';
INSERT wtf SET acronym_i = 'veg', acronym = 'VEG', text = 'very evil grin';
INSERT wtf SET acronym_i = 'w/', acronym = 'W/', text = 'with';
INSERT wtf SET acronym_i = 'w/o', acronym = 'W/O', text = 'without';
INSERT wtf SET acronym_i = 'wag', acronym = 'WAG', text = 'wild-ass guess';
INSERT wtf SET acronym_i = 'wb', acronym = 'WB', text = 'welcome back';
INSERT wtf SET acronym_i = 'wfm', acronym = 'WFM', text = 'works for me';
INSERT wtf SET acronym_i = 'wibni', acronym = 'WIBNI', text = 'wouldn\'t it be nice if';
INSERT wtf SET acronym_i = 'wip', acronym = 'WIP', text = 'work in progress';
INSERT wtf SET acronym_i = 'woftam', acronym = 'WOFTAM', text = 'waste of fucking time and money';
INSERT wtf SET acronym_i = 'wombat', acronym = 'WOMBAT', text = 'waste of money, brain, and time';
INSERT wtf SET acronym_i = 'wrt', acronym = 'WRT', text = 'with respect to';
INSERT wtf SET acronym_i = 'wtf', acronym = 'WTF', text = '{what,where,who,why} the fuck';
INSERT wtf SET acronym_i = 'wth', acronym = 'WTH', text = '{what,where,who,why} the hell';
INSERT wtf SET acronym_i = 'wysiwyg', acronym = 'WYSIWYG', text = 'what you see is what you get';
INSERT wtf SET acronym_i = 'yalimo', acronym = 'YALIMO', text = 'you are lame, in my opinion';
INSERT wtf SET acronym_i = 'yhbt', acronym = 'YHBT', text = 'you have been trolled';
INSERT wtf SET acronym_i = 'yhl', acronym = 'YHL', text = 'you have lost';
INSERT wtf SET acronym_i = 'ykwim', acronym = 'YKWIM', text = 'you know what I mean';
INSERT wtf SET acronym_i = 'yma', acronym = 'YMA', text = 'yo momma\'s ass';
INSERT wtf SET acronym_i = 'ymmv', acronym = 'YMMV', text = 'your mileage may vary';
INSERT wtf SET acronym_i = 'yw', acronym = 'YW', text = 'you\'re welcome';
