#!/usr/bin/perl -w

############################################################
# A small little hook to parse the channel chat for URLs   #
# and make Tinyurls out of them. As requested by cshields. #
# Patched because of fox2mike :)                           #
############################################################

use URI::Find::Rule;
use WWW::Shorten::TinyURL;
use WWW::Shorten 'TinyURL';
use Regexp::Assemble;
use Hackabot::Client;

my $hbc = Hackabot::Client->new;
my $ra = Regexp::Assemble->new;
my $conf = $hbc->{'conf'}->{'hooks'};
my $nick = $ENV{'HBEV_SENT_BY'};
my $msg = <>;

if(exists $conf->{'tinyurl'}){
    if(ref($conf->{'tinyurl'}) eq "ARRAY"){
        foreach (@{$conf->{'tinyurl'}}){
            if(exists $_->{'ignore'}){
                $ra->add($_->{'ignore'});
            }
        }
    } else {
        $ra->add($conf->{'tinyurl'}->{'ignore'});
    }
}

my @urls = URI::Find::Rule->in($msg, 1);
if(@urls){
    foreach $url (@urls){
        if(length($url->as_string) > 79){
            if($url->as_string !~ m/$ra/i){
                $short_url = makeashorterlink($url->as_string);
                print "msg $nick\'s tiny URL is $short_url\n";
            }
        }
    }
}
