#!/usr/bin/perl -w

##HACKABOT_HELP##
# Get the answers to life!
# !8ball
##HACKABOT_HELP##

use strict;

#my ($nick, $msg);
#while (<>) {
#	if (/^nick\s*(\S*)/) {
#		$nick = $1;
#	}
#	elsif (/^msg\s*(.*)/) {
#		$msg = $1;
#	}
#}

my @answers = (
"     ___
    /   \\
   /     \\
  / IT IS \\
 / CERTAIN \\
/           \\
\\___________/
",
"     ___
    /   \\
   /     \\
  /  MY   \\
 / SOURCES \\
/  SAY  NO  \\
\\___________/
",
"     ___
    /   \\
   /     \\
  /  MY   \\
 / SOURCES \\
/  SAY YES  \\
\\___________/
",
" ___________
/           \\
\\   MOST    /
 \\ LIKELY  /
  \\  NOT  /
   \\     /
    \\___/
",
" ___________
/           \\
\\           /
 \\ UMMM..  /
  \\   NO  /
   \\     /
    \\___/
",
" ___________
/           \\
\\  WITHOUT  /
 \\    A    /
  \\ DOUBT /
   \\     /
    \\___/
",
"     ___
    /   \\
   /     \\
  / VERY  \\
 /         \\
/  DOUBTFUL \\
\\___________/
",
"     ___
    /   \\
   /     \\
  /       \\
 /    NO   \\
/           \\
\\___________/
",
"     ___
    /   \\
   /     \\
  /       \\
 /   YES   \\
/           \\
\\___________/
",
" ___________
/           \\
\\     I     /
 \\  DON'T  /
  \\ CARE  /
   \\     /
    \\___/
",
" ___________
/           \\
\\           /
 \\  HECK   /
  \\  YEA! /
   \\     /
    \\___/
");


print "sendnext\n";
print $answers[int(rand(@answers))];

