#!/bin/bash

##HACKABOT_HELP##
# About this Bot
# !about
##HACKABOT_HELP##

echo "sendnext"
echo "Hackabot :: Version [something between 0 and 1]"
echo "URLs: https://lug.oregonstate.edu/svn/hackabot/"
echo "      https://lug.oregonstate.edu/websvn/"
echo "      http://code.google.com/p/hackabot/issues/list"
