#!/usr/bin/perl -w

##HACKABOT_HELP##
# Get the answers to life!
# !answer
##HACKABOT_HELP##

use strict;

my $nick = $ENV{'HBEV_SENT_BY'};

my @answers = (
"It is certain.",
"My sources say no.",
"My sources say yes.",
"Most likely not.",
"UMMM.. No.",
"Without a doubt.",
"Very doubtful.",
"No",
"Yes",
"I don't care.",
"Heck Yea!");

print "send $nick: ".$answers[int(rand(@answers))];

