#!/usr/bin/perl -w

##HACKABOT_HELP##
# Blame someone in the channel for the horrible things they did.
# !blame [something bad]
##HACKABOT_HELP##

use strict;
use URI::Escape;

my ($chan, $msg);
while (<>) {
	if (/^type\s+privmsg/) {
		print "send I blame you!";
		exit;
	}
	elsif (/^to\s+(.+)/) {
		$chan = $1;
	}
	elsif (/^msg\s+(.+)/) {
		$msg = $1;
	}
}

my @canned = (
	"Windows NT",
	"morning breath",
	"world hunger",
	"global warming",
	"Bush" );
if (not defined $msg) {
	$msg = $canned[int(rand(@canned))];
}

if (defined $msg and defined $chan) {
	my $names = `echo "names $chan" | $ENV{'HACKABOT_DIR'}/scripts/client`;
	chomp $names;
	$names =~ s/^\S+\s+\S+\s+//;
	$names =~ s/\smanatee_*//g;
	my @list = split(/\s+/, $names);
	my $name = $list[int(rand(@list))];
	print "me blames $name for $msg.\n";
}
else {
	die "blame: All info not found :-/\n";
}
