#!/bin/bash

##HACKABOT_HELP##
# What distro will someone try next?
# !distro
##HACKABOT_HELP##

echo sendnext
lynx -dump http://distrowatch.com/ | grep "^  *`echo "(${RANDOM}00 / 32767)+1" | bc`  *" | perl -p -e 's/^.*\[.*\](\S+.*\S+)\s+\d+\s+\S+$/$1/;'
