#!/bin/bash

echo "sendnext"
echo ' _______________________________________________'
echo "/ Oregon State - It really whips the cow's ass! \\"
echo "\\                           Go Beavs!           /"
echo ' -----------------------------------------------'
echo '        \   ^__^'
echo '         \  (oo)\_______'
echo '            (__)\       )\/\'
echo '                ||----w |'
echo '                ||     ||'
