#!/usr/bin/perl -w

##HACKABOT_HELP##
# Do you feel lucky?
# !google search phrase
##HACKABOT_HELP##

use strict;
use Net::Google;
use URI::Escape;
use XML::Simple;

my $CONFIG = XMLin($ENV{'HACKABOT_CFG'});
my $CMDCFG = $CONFIG->{'cmdconfig'}->{'google'};

my ($search, $asker);
while (<>) {
	if (/^nick\s*(\S*)/) {
		$asker = $1;
	}
	elsif (/^msg\s*(.*)/) {
		$search = $1;
	}
}

if (defined $search and defined $asker) {
	my $url = geturl($search);
	if (defined $url) {
		print "send $asker: $url\n";
	}
	else {
		print "send $asker: Google didn't say much :-/\n";
	}
}
else {
	die "google: All info not found :-/\n";
}

sub geturl {
	my $word = shift;

	if (not defined $word) {
		die "google: geturl needs an argument!";
	}
	
	my $google = Net::Google->new(key=>$CMDCFG->{'apikey'}, max_results=>1);
	my $search = $google->search();

	$search->query($word);
	my @responses = @{$search->results()};
	if (defined $responses[0]) {
		return $responses[0]->URL();
	}
	else {
		return undef;
	}
}
