#!/usr/bin/perl -w

##HACKABOT_HELP##
# Tell someone rude and confusing!
# !insult [#chan] nick
##HACKABOT_HELP##

use strict;
use LWP::Simple;

my $msg = <>;
if (defined $msg) {
    chomp $msg;
    if ($msg =~ /(#\S+)\s+(.*)/) {
        my $insult = insult();
        print "to $1\n";
        print "send $2: $insult\n";
    }
    else {
        my $insult = insult();
        print "send $msg: $insult\n";
    }
}

sub insult {
    my $insult = get("http://www.webweaving.org/");

    if ($insult =~ /(Thou\s[^\n]*)/) {
        $insult = $1;
        chomp $insult;
        return "$insult!";
    }
    else {
        return "I Love You!";
    }
}
