#!/bin/bash

##HACKABOT_HELP##
# emerge moo
# !moo
##HACKABOT_HELP##

echo "sendnext"
echo '  Gentoo (Linux)'
echo
echo ' _______________________'
echo '< Have you mooed today? >'
echo ' -----------------------'
echo '        \   ^__^'
echo '         \  (oo)\_______'
echo '            (__)\       )\/\'
echo '                ||----w |'
echo '                ||     ||'
