#!/bin/bash

##HACKABOT_HELP##
# Display a url on bigscreen
# !onscreen on | off | reset | URL
##HACKABOT_HELP##

echo "sendnext"
URL="`grep '^msg' | sed -e 's/^msg\s*//g' | sed -e "s/'//g"`"
ssh monitor@bigscreen -x "~/on-web '$URL'"
