#!/bin/bash

##HACKABOT_HELP##
# Get a random proverb
# !proverb
##HACKABOT_HELP##


echo sendnext
lynx -dump -width 1000 http://www.special-dictionary.com/proverbs/random/ | \
	grep -m 1 -A 2 '^ *\"' | tr '\n' ' ' | \
	perl -p -e 's/\s{2,}//g; s/\[\d+\]/ -- /'
