#!/usr/bin/perl -w

##HACKABOT_HELP##
# Send a message
# !sayto [#chan] something to say
##HACKABOT_HELP##

use strict;

use XML::Simple;
use IO::Handle;
STDOUT->autoflush(1);

my $msg;
while (<>) {
	if (/^msg\s*(.*)/) {
		$msg = $1;
	}
}

if (defined $msg) {
	if ($msg =~ /(#\S+)\s+(.+)/) {
		print "to $1\n";
		print "send $2\n";
	}
	else {
		print "send Usage: !sayto #chan Some text to say";
	}
}
