#!/usr/bin/perl -w

##HACKABOT_HELP##
# Who is asleep? 
# !sleep [#chan]
##HACKABOT_HELP##

use strict;
use DBI;
use Time::localtime;
use XML::Simple;

my $privmsg = 0;
my ($chan, $nick, $to);
while (<>) {
	if (/^type\s+privmsg/) {
		$privmsg = 1;
	}
	elsif (/^to\s+(\S+)/) {
		$chan = $1;
	}
	elsif (/^nick\s+(\S+)/) {
		$nick = $1;
	}
	elsif (/^msg\s+(#\S+)/) {
		$to = $1;
	}
}

if ($privmsg and not defined $to) {
	print "send zzzzzzz\n";
	exit;
}

if (defined $chan and defined $nick) {
	if (defined $to) {
		print "to $to\n";
	}
	print "send you may be asleep but $nick is not.\n";
}

