#!/bin/bash

##HACKABOT_HELP##
# Set the volume on bigscreen
# !volume ##
##HACKABOT_HELP##

#echo "sendnext"
VOL=`grep '^msg' | sed -e 's/^msg\s*//g'`
ssh monitor@bigscreen -x "/usr/bin/amixer set Master $VOL% && /usr/bin/amixer set Master unmute" > /dev/null 2>&1
