#!/bin/bash

##HACKABOT_HELP##
# What is Eric going to buy today?
# !woot
##HACKABOT_HELP##

echo sendnext
curl -s http://www.woot.com/blog/rss.aspx | grep -m2 "<title>" | \
    tail -n1 | sed -e 's%.*<title>\(.*\)</title>.*%\1%'
