#!/usr/bin/perl

use strict;
use DBI;
use Time::localtime;
use XML::Simple;

my $CONFIG = XMLin($ENV{'HACKABOT_CFG'});
my $DBCFG = $CONFIG->{'cmdconfig'}->{'database'};

my $dbhost = $DBCFG->{'host'};
my $dbname = $DBCFG->{'name'};
my $dbuser = $DBCFG->{'user'};
my $dbpass = $DBCFG->{'pass'};

my ($type, $chan, $msg, $nick);
while (<>) {
	if (/^type\s+(\S+)/) {
		$type = $1;
	}
	elsif (/^nick\s*(\S*)/) {
		$nick = $1;
	}
	elsif (/^to\s*(\S*)/) { # We assume there is only one name listed
		$chan = $1;
	}
	elsif (/^msg\s*!s[\/\s]/) {
		exit; # I don't care about seeing !s
	}
	elsif (/^msg\s*(.*)/) {
		$msg = $1;
	}
}

if (defined $nick and defined $type) {
	my ($dbh, $sth);

	$dbh = DBI->connect("DBI:mysql:$dbname:$dbhost", $dbuser, $dbpass, { PrintError => 1 });
	if (!$dbh) {
		die "log: Failed to connect to database\n";
	}
	
	my $time = `date "+%F %R"`;
	chomp $time;

	if ($type =~ m/msg/ or $type =~ m/snd/) {
		$type = "msg";
	}

	if (not ($type eq "msg" or $type eq "action" or $type eq "notice" or
		$type eq "join" or $type eq "part" or $type eq "quit")) {
		die "logger: Unknown type '$type', add it to the enum!\n";
	}

	$nick = $dbh->quote($nick);
	$time = $dbh->quote($time);
	$type = $dbh->quote($type);
	
	if (defined $msg) {
		$msg = $dbh->quote($msg);
	}
	else {
		$msg = "NULL";
	}
	if (defined $chan and $chan =~ m/^#/) {
		$chan = $dbh->quote($chan);
	}
	else {
		$chan = "NULL";
	}
	$dbh->do("INSERT log SET date = $time, text = $msg, chan = $chan, nick = $nick, type = $type") or die "log: DB stuff failed.\n";

	$dbh->disconnect;
}
else {
	die "log: All info not found :-/\n";
}
