#!/usr/bin/perl -w

use strict;

use XML::Simple;
use IO::Handle;
STDOUT->autoflush(1);

my $arg = shift;
if  (not $arg eq "msg") {
	exit;	
}

my $CONFIG = XMLin("$ENV{'HOME'}/.hackabot.xml", 
	ForceArray => ['automsg', 'autojoin']);

my $MODS = $CONFIG->{'directory'}."/".$CONFIG->{'modules'};

print "send\n";

my $send = "Commands:";
opendir(MODDIR, $MODS);
while ($_ = readdir(MODDIR)) {
	if (/^[^\.]/ and -x "/$MODS/$_") {
		$send .= " $_";
	}
}
closedir(MODDIR);
print "$send\n";
