#!/usr/bin/perl -w

use strict;

use IO::Handle;
STDOUT->autoflush(1);

my ($msg, $nick);
while (<>) {
	if (/^msg\s*(.*)/) {
		$msg = $1;
	}
	elsif (/^nick\s+(.+)/) {
		$nick = $1;
	}
}

if (defined $msg and defined $nick) {
	if ($msg =~ /!slogan\s+.*(windows\s*xp)/i) {
		print "nocmd\n";
		print "send $nick: $1 suckzors!\n";
	}
}
